import * as React from 'react';
import * as UnisIcons from '../../src';

function App() {
  return (
    <div className="max-w-sm m-auto p-4 flex flex-wrap text-gray-900">
      <UnisIcons.Logo3M />
      <UnisIcons.ActiveDirectoryLogo />
      <UnisIcons.AdaLogo />
      <UnisIcons.AdobeLogo />
      <UnisIcons.AhaLogo />
      <UnisIcons.AhrefLogo />
      <UnisIcons.AjaxLogo />
      <UnisIcons.AlertMediaLogo />
      <UnisIcons.AlipayLogo />
      <UnisIcons.AmazonAlexaLogo />
      <UnisIcons.AmazonLogo />
      <UnisIcons.AmazonPrimeVideoLogo />
      <UnisIcons.AmericanAcademyOfForensicSciencesLogo />
      <UnisIcons.AmericanCancerSocietyLogo />
      <UnisIcons.AmericanExpressLogo />
      <UnisIcons.AmericanNationalStandardsInstituteLogo />
      <UnisIcons.AmericanRedCrossLogo />
      <UnisIcons.AmexCardLogo />
      <UnisIcons.AmpLogo />
      <UnisIcons.AndroidLogo />
      <UnisIcons.AndroidOldLogo />
      <UnisIcons.AngularLogo />
      <UnisIcons.ApacheAirflowLogo />
      <UnisIcons.AppleCareLogo />
      <UnisIcons.AshpLogo />
      <UnisIcons.AssociationForTheAdvancementOfBloodBiotherapiesLogo />
      <UnisIcons.AssociationOfAmericanMedicalCollegeLogo />
      <UnisIcons.AstmInternationalLogo />
      <UnisIcons.AtlassianLogo />
      <UnisIcons.AtomLogo />
      <UnisIcons.AutodeskLogo />
      <UnisIcons.AvadeWorkplaceViolencePreventionLogo />
      <UnisIcons.AvanadeLogo />
      <UnisIcons.AxureLogo />
      <UnisIcons.AxwayLogo />
      <UnisIcons.AzureLogo />
      <UnisIcons.BackboneJsLogo />
      <UnisIcons.BanContactLogo />
      <UnisIcons.BehanceLogo />
      <UnisIcons.BeyondTrustLogo />
      <UnisIcons.BlueCrossBlueShieldLogo />
      <UnisIcons.BrandfolderLogo />
      <UnisIcons.BrazeLogo />
      <UnisIcons.BrightcoveLogo />
      <UnisIcons.CPanelLogo />
      <UnisIcons.CapsulePharmacyLogo />
      <UnisIcons.CdwLogo />
      <UnisIcons.CentersForDiseaseControlLogo />
      <UnisIcons.ChecklyLogo />
      <UnisIcons.CignaLogo />
      <UnisIcons.CitrixLogo />
      <UnisIcons.CodepenLogo />
      <UnisIcons.ContentfulLogo />
      <UnisIcons.CorVelCorporationLogo />
      <UnisIcons.CyberArkLogo />
      <UnisIcons.DbtLabsLogo />
      <UnisIcons.DepartmentOfHealthHumanServicesLogo />
      <UnisIcons.DepartmentOfHomelandSecurityLogo />
      <UnisIcons.DinersClubLogo />
      <UnisIcons.DiscordLogo />
      <UnisIcons.DiscoverLogo />
      <UnisIcons.DockerLogo />
      <UnisIcons.DocuSignLogo />
      <UnisIcons.DocumentumLogo />
      <UnisIcons.DribbbleLogo />
      <UnisIcons.DropboxLogo />
      <UnisIcons.DrugEnforcementAdministrationLogo />
      <UnisIcons.EclipseLogo />
      <UnisIcons.ElasticLogo />
      <UnisIcons.ElsevierLogo />
      <UnisIcons.EngageLogo />
      <UnisIcons.EnvironmentalProtectionAgencyLogo />
      <UnisIcons.EpicLogo />
      <UnisIcons.EthereumLogo />
      <UnisIcons.EventbriteLogo />
      <UnisIcons.ExperianLogo />
      <UnisIcons.FacebookLogo />
      <UnisIcons.FacebookWatchLogo />
      <UnisIcons.FedExLogo />
      <UnisIcons.FederalCommunicationsCommissionLogo />
      <UnisIcons.FigmaLogo />
      <UnisIcons.FirebaseLogo />
      <UnisIcons.FisherCenterForAlzheimerSResearchFoundationLogo />
      <UnisIcons.FlaskLogo />
      <UnisIcons.FoodAndDrugAdministrationLogo />
      <UnisIcons.GPayLogo />
      <UnisIcons.GiropayLogo />
      <UnisIcons.GitBookLogo />
      <UnisIcons.GitHubLogo />
      <UnisIcons.GitLogo />
      <UnisIcons.GlitchLogo />
      <UnisIcons.GocdLogo />
      <UnisIcons.GoogleFontsLogo />
      <UnisIcons.GoogleGSuiteLogo />
      <UnisIcons.GoogleLensLogo />
      <UnisIcons.GoogleLogo />
      <UnisIcons.GoogleMapsLogo />
      <UnisIcons.GooglePayAltLogo />
      <UnisIcons.GooglePayLogo />
      <UnisIcons.GooglePlayLogo />
      <UnisIcons.GrammarlyLogo />
      <UnisIcons.HaikuLogo />
      <UnisIcons.HashnodeLogo />
      <UnisIcons.HumanaLogo />
      <UnisIcons.IOsLogo />
      <UnisIcons.IbmLogo />
      <UnisIcons.IftttLogo />
      <UnisIcons.InstagramLogo />
      <UnisIcons.IntuitLogo />
      <UnisIcons.InvisionLogo />
      <UnisIcons.JQueryLogo />
      <UnisIcons.KlarnaAltLogo />
      <UnisIcons.KlarnaLogo />
      <UnisIcons.KronosLogo />
      <UnisIcons.LambdaTestLogo />
      <UnisIcons.LastPassLogo />
      <UnisIcons.LevelAccessLogo />
      <UnisIcons.LinkedInLogo />
      <UnisIcons.LookerLogo />
      <UnisIcons.LucidchartLogo />
      <UnisIcons.MacOsLogo />
      <UnisIcons.MaestroLogo />
      <UnisIcons.MailchimpLogo />
      <UnisIcons.MariaDbLogo />
      <UnisIcons.MastercardLogo />
      <UnisIcons.MazeLogo />
      <UnisIcons.MediumLogo />
      <UnisIcons.MetLifeLogo />
      <UnisIcons.MeteorLogo />
      <UnisIcons.MicrosoftLogo />
      <UnisIcons.MicrosoftNetLogo />
      <UnisIcons.MiroLogo />
      <UnisIcons.MixpanelLogo />
      <UnisIcons.ModernaLogo />
      <UnisIcons.MyMicroLogo />
      <UnisIcons.NcrLogo />
      <UnisIcons.NestLogo />
      <UnisIcons.NextdoorLogo />
      <UnisIcons.NginxLogo />
      <UnisIcons.NpmLogo />
      <UnisIcons.NuanceLogo />
      <UnisIcons.NuxtJsLogo />
      <UnisIcons.NvidiaLogo />
      <UnisIcons.OfficeDepotLogo />
      <UnisIcons.OneCallLogo />
      <UnisIcons.OpenstackLogo />
      <UnisIcons.OracleLogo />
      <UnisIcons.PayPalLogo />
      <UnisIcons.PayoneerLogo />
      <UnisIcons.PaysafeLogo />
      <UnisIcons.PercyLogo />
      <UnisIcons.PfizerLogo />
      <UnisIcons.PhoenixSocietyForBurnSurvivorsLogo />
      <UnisIcons.PhpLogo />
      <UnisIcons.PingIdentityLogo />
      <UnisIcons.PinterestLogo />
      <UnisIcons.PostmanLogo />
      <UnisIcons.PowerToDecideLogo />
      <UnisIcons.QualtricsProductExperienceLogo />
      <UnisIcons.QualtricsXmLogo />
      <UnisIcons.RailsLogo />
      <UnisIcons.RedHatLogo />
      <UnisIcons.ReductVideoLogo1Logo />
      <UnisIcons.SemanticWebLogo />
      <UnisIcons.SepaLogo />
      <UnisIcons.ServiceNowLogo />
      <UnisIcons.SharecareLogo />
      <UnisIcons.SitecoreLogo />
      <UnisIcons.SketchLogo />
      <UnisIcons.SkrillLogo />
      <UnisIcons.SlackLogo />
      <UnisIcons.SnagitLogo />
      <UnisIcons.SofortLogo />
      <UnisIcons.SolrLogo />
      <UnisIcons.SonarQubeLogo />
      <UnisIcons.SoundcloudLogo />
      <UnisIcons.SplitLogo />
      <UnisIcons.SplunkLogo />
      <UnisIcons.SpotifyLogo />
      <UnisIcons.SqLiteLogo />
      <UnisIcons.StorybookLogo />
      <UnisIcons.StripeLogo />
      <UnisIcons.SublimeTextLogo />
      <UnisIcons.SumoLogicLogo />
      <UnisIcons.SuzyLogo />
      <UnisIcons.SvelteLogo />
      <UnisIcons.SymantecLogo />
      <UnisIcons.TableauLogo />
      <UnisIcons.TailwindCssLogo />
      <UnisIcons.TalkspaceLogo />
      <UnisIcons.TbAllianceLogo />
      <UnisIcons.TechSmithLogo />
      <UnisIcons.TecsysLogo />
      <UnisIcons.TerraformLogo />
      <UnisIcons.TestCafeLogo />
      <UnisIcons.TestProjectLogo />
      <UnisIcons.TheHastingsCenterLogo />
      <UnisIcons.TikTokLogo />
      <UnisIcons.TorLogo />
      <UnisIcons.TumblrLogo />
      <UnisIcons.TwilioLogo />
      <UnisIcons.TwitchLogo />
      <UnisIcons.TypeScriptLogo />
      <UnisIcons.TypeformLogo />
      <UnisIcons.UberLogo />
      <UnisIcons.UpsLogo />
      <UnisIcons.UsdaLogo />
      <UnisIcons.UserTestingLogo />
      <UnisIcons.UserZoomLogo />
      <UnisIcons.VMwareLogo />
      <UnisIcons.VimeoLogo />
      <UnisIcons.VisaElectronLogo />
      <UnisIcons.VisaLogo />
      <UnisIcons.WalgreensLogo />
      <UnisIcons.WeTransferLogo />
      <UnisIcons.WebDevLogo />
      <UnisIcons.WebmoneyLogo />
      <UnisIcons.WikipediaLogo />
    </div>
  );
}

export default App;
