import * as React from 'react';
import * as UnisIcons from '../../src';

function App() {
  return (
    <div className="max-w-sm m-auto p-4 flex flex-wrap text-gray-900">
      <UnisIcons.AdobeAcrobatAltIcon />
      <UnisIcons.AdobeAcrobatIcon />
      <UnisIcons.AdobeAeroIcon />
      <UnisIcons.AdobeAfterEffectsIcon />
      <UnisIcons.AdobeAnimateIcon />
      <UnisIcons.AdobeAuditionIcon />
      <UnisIcons.AdobeCreativecloudAltIcon />
      <UnisIcons.AdobeCreativecloudIcon />
      <UnisIcons.AdobeDimensionIcon />
      <UnisIcons.AdobeDreamweaverIcon />
      <UnisIcons.AdobeFillAndSignIcon />
      <UnisIcons.AdobeIcon />
      <UnisIcons.AdobeIllustratorIcon />
      <UnisIcons.AdobeIncopyIcon />
      <UnisIcons.AdobeLightroomIcon />
      <UnisIcons.AdobePhotoshopCameraIcon />
      <UnisIcons.AdobePhotoshopExpressIcon />
      <UnisIcons.AdobePhotoshopIcon />
      <UnisIcons.AdobePremiereIcon />
      <UnisIcons.AdobePremiereRushIcon />
      <UnisIcons.AdobeSignIcon />
      <UnisIcons.AdobeSparkIcon />
      <UnisIcons.AdobeStockIcon />
      <UnisIcons.AdobeXdIcon />
      <UnisIcons.AirbnbIcon />
      <UnisIcons.AirflowIcon />
      <UnisIcons.AirtableIcon />
      <UnisIcons.AlertmediaIcon />
      <UnisIcons.AlfaBankIcon />
      <UnisIcons.AmazonAlexaIcon />
      <UnisIcons.AmazonIcon />
      <UnisIcons.AmazonPayIcon />
      <UnisIcons.AmazonWebServicesIcon />
      <UnisIcons.AmdIcon />
      <UnisIcons.AmericanExpressIcon />
      <UnisIcons.AmpIcon />
      <UnisIcons.AmwellIcon />
      <UnisIcons.AndroidAutoIcon />
      <UnisIcons.AndroidIcon />
      <UnisIcons.AngelListIcon />
      <UnisIcons.AngularIcon />
      <UnisIcons.ApacheIcon />
      <UnisIcons.AppcodeIcon />
      <UnisIcons.AppiumIcon />
      <UnisIcons.AppleAppStoreAltIcon />
      <UnisIcons.AppleAppStoreIcon />
      <UnisIcons.AppleCarplayIcon />
      <UnisIcons.AppleFacetimeIcon />
      <UnisIcons.AppleFinderIcon />
      <UnisIcons.AppleHomekitIcon />
      <UnisIcons.AppleIcloudIcon />
      <UnisIcons.AppleIcon />
      <UnisIcons.AppleMacintoshIcon />
      <UnisIcons.AppleMessagesIcon />
      <UnisIcons.AppleMusicIcon />
      <UnisIcons.ApplePayIcon />
      <UnisIcons.ApplePodcastsIcon />
      <UnisIcons.AppleSiriIcon />
      <UnisIcons.AppleTvIcon />
      <UnisIcons.AskfmIcon />
      <UnisIcons.AtlassianIcon />
      <UnisIcons.AtomIcon />
      <UnisIcons.AudibleIcon />
      <UnisIcons.Auth0Icon />
      <UnisIcons.AwsCloudwatchIcon />
      <UnisIcons.AwsLambdaIcon />
      <UnisIcons.AxwayIcon />
      <UnisIcons.AzureActiveDirectoryIcon />
      <UnisIcons.AzureDevopsIcon />
      <UnisIcons.AzureIcon />
      <UnisIcons.BackboneJsIcon />
      <UnisIcons.BadooIcon />
      <UnisIcons.BambooIcon />
      <UnisIcons.BasecampIcon />
      <UnisIcons.BehanceAltIcon />
      <UnisIcons.BehanceIcon />
      <UnisIcons.BingAltIcon />
      <UnisIcons.BingIcon />
      <UnisIcons.BitbucketIcon />
      <UnisIcons.BitcoinIcon />
      <UnisIcons.BlackberryIcon />
      <UnisIcons.BlocsIcon />
      <UnisIcons.BloggerIcon />
      <UnisIcons.BluetoothIcon />
      <UnisIcons.BootstrapIcon />
      <UnisIcons.BowerIcon />
      <UnisIcons.BrandfolderIcon />
      <UnisIcons.BraveIcon />
      <UnisIcons.BrightcoveIcon />
      <UnisIcons.BrowserstackIcon />
      <UnisIcons.BugherdIcon />
      <UnisIcons.CIcon />
      <UnisIcons.CPlusplusIcon />
      <UnisIcons.CSharpIcon />
      <UnisIcons.CakePhpIcon />
      <UnisIcons.ChaiIcon />
      <UnisIcons.CirrusIcon />
      <UnisIcons.CitrixIcon />
      <UnisIcons.ClippyIcon />
      <UnisIcons.CloudinaryIcon />
      <UnisIcons.CodepenIcon />
      <UnisIcons.ConfluenceIcon />
      <UnisIcons.ContactlessPaymentIcon />
      <UnisIcons.ContentfulIcon />
      <UnisIcons.CoubIcon />
      <UnisIcons.CrossBrowserTestingIcon />
      <UnisIcons.Css3Icon />
      <UnisIcons.CyberarkIcon />
      <UnisIcons.CypressIcon />
      <UnisIcons.DartIcon />
      <UnisIcons.DellIcon />
      <UnisIcons.DinersClubIcon />
      <UnisIcons.DirectDebitIcon />
      <UnisIcons.DiscordAltIcon />
      <UnisIcons.DiscordIcon />
      <UnisIcons.DjangoIcon />
      <UnisIcons.DockerIcon />
      <UnisIcons.DocumentumIcon />
      <UnisIcons.DogecoinIcon />
      <UnisIcons.DribbbleIcon />
      <UnisIcons.DropboxAltIcon />
      <UnisIcons.DropboxIcon />
      <UnisIcons.DrupalIcon />
      <UnisIcons.DuckduckgoIcon />
      <UnisIcons.Dynamics365Icon />
      <UnisIcons.DynamicsBusinessCentralIcon />
      <UnisIcons.DynamicsCommerceIcon />
      <UnisIcons.DynamicsCrmIcon />
      <UnisIcons.DynamicsHrIcon />
      <UnisIcons.DynamicsSupplyChainManagementIcon />
      <UnisIcons.EclipseIcon />
      <UnisIcons.EdgeLegacyIcon />
      <UnisIcons.ElementaryIcon />
      <UnisIcons.EmmetIcon />
      <UnisIcons.EmporosIcon />
      <UnisIcons.Es6Icon />
      <UnisIcons.EslintIcon />
      <UnisIcons.EthereumIcon />
      <UnisIcons.EventbriteIcon />
      <UnisIcons.EvernoteIcon />
      <UnisIcons.FacebookAltIcon />
      <UnisIcons.FacebookIcon />
      <UnisIcons.FacebookLiveIcon />
      <UnisIcons.FacebookMessengerIcon />
      <UnisIcons.FacebookWatchIcon />
      <UnisIcons.FacebookWorkplaceIcon />
      <UnisIcons.FedoraIcon />
      <UnisIcons.FigmaIcon />
      <UnisIcons.FirebaseIcon />
      <UnisIcons.FirefoxBrowserIcon />
      <UnisIcons.FirefoxIcon />
      <UnisIcons.FitbitIcon />
      <UnisIcons.FlatUiIcon />
      <UnisIcons.FlickrIcon />
      <UnisIcons.FlutterIcon />
      <UnisIcons.FontawesomeIcon />
      <UnisIcons.FoursquareAltIcon />
      <UnisIcons.FoursquareIcon />
      <UnisIcons.FramerIcon />
      <UnisIcons.FreebsdIcon />
      <UnisIcons.FuchsiaIcon />
      <UnisIcons.GatsbyIcon />
      <UnisIcons.GerritIcon />
      <UnisIcons.GitIcon />
      <UnisIcons.GitbookIcon />
      <UnisIcons.GithubIcon />
      <UnisIcons.GitkrakenIcon />
      <UnisIcons.GitlabIcon />
      <UnisIcons.GlitchIcon />
      <UnisIcons.GmailIcon />
      <UnisIcons.GnomeIcon />
      <UnisIcons.GoIcon />
      <UnisIcons.Google360SuiteIcon />
      <UnisIcons.GoogleAdManagerIcon />
      <UnisIcons.GoogleAdmobIcon />
      <UnisIcons.GoogleAdsIcon />
      <UnisIcons.GoogleAdsenseIcon />
      <UnisIcons.GoogleAiIcon />
      <UnisIcons.GoogleAnalyticsIcon />
      <UnisIcons.GoogleArcoreIcon />
      <UnisIcons.GoogleAssistantIcon />
      <UnisIcons.GoogleAuthenticatorIcon />
      <UnisIcons.GoogleCalendarIcon />
      <UnisIcons.GoogleChatIcon />
      <UnisIcons.GoogleChromeIcon />
      <UnisIcons.GoogleChromiumIcon />
      <UnisIcons.GoogleClassroomIcon />
      <UnisIcons.GoogleCloudFunctionsIcon />
      <UnisIcons.GoogleCloudIcon />
      <UnisIcons.GoogleCloudRunIcon />
      <UnisIcons.GoogleCollectionsIcon />
      <UnisIcons.GoogleCurrentsIcon />
      <UnisIcons.GoogleDataStudioIcon />
      <UnisIcons.GoogleDiscoverIcon />
      <UnisIcons.GoogleDisplayAndVideoAdsIcon />
      <UnisIcons.GoogleDocsIcon />
      <UnisIcons.GoogleDomainsIcon />
      <UnisIcons.GoogleDoubleclickIcon />
      <UnisIcons.GoogleDownasaurIcon />
      <UnisIcons.GoogleDrawingsIcon />
      <UnisIcons.GoogleDriveIcon />
      <UnisIcons.GoogleDuoIcon />
      <UnisIcons.GoogleEarthIcon />
      <UnisIcons.GoogleFilesIcon />
      <UnisIcons.GoogleFitIcon />
      <UnisIcons.GoogleFontsIcon />
      <UnisIcons.GoogleFormsIcon />
      <UnisIcons.GoogleHangoutsIcon />
      <UnisIcons.GoogleHomeIcon />
      <UnisIcons.GoogleIcon />
      <UnisIcons.GoogleKeepIcon />
      <UnisIcons.GoogleLensIcon />
      <UnisIcons.GoogleLighthouseIcon />
      <UnisIcons.GoogleMapsIcon />
      <UnisIcons.GoogleMarketingPlatformIcon />
      <UnisIcons.GoogleMeetIcon />
      <UnisIcons.GoogleMerchantCenterIcon />
      <UnisIcons.GoogleMyBusinessIcon />
      <UnisIcons.GoogleNearbyIcon />
      <UnisIcons.GoogleNewsIcon />
      <UnisIcons.GoogleOneIcon />
      <UnisIcons.GoogleOptimizeIcon />
      <UnisIcons.GooglePayAltIcon />
      <UnisIcons.GooglePayIcon />
      <UnisIcons.GooglePhotosIcon />
      <UnisIcons.GooglePlayIcon />
      <UnisIcons.GooglePlayMusicIcon />
      <UnisIcons.GooglePlayServicesIcon />
      <UnisIcons.GooglePodcastIcon />
      <UnisIcons.GoogleScholarIcon />
      <UnisIcons.GoogleSearchAdsIcon />
      <UnisIcons.GoogleSheetsIcon />
      <UnisIcons.GoogleShoppingIcon />
      <UnisIcons.GoogleSitesIcon />
      <UnisIcons.GoogleSlidesIcon />
      <UnisIcons.GoogleStadiaIcon />
      <UnisIcons.GoogleStreetviewIcon />
      <UnisIcons.GoogleSurveysIcon />
      <UnisIcons.GoogleTagAssistantIcon />
      <UnisIcons.GoogleTagManagerIcon />
      <UnisIcons.GoogleTranslateIcon />
      <UnisIcons.GoogleTvIcon />
      <UnisIcons.GoogleUnverifiedIcon />
      <UnisIcons.GoogleVerifiedIcon />
      <UnisIcons.GoogleVerifiedbadgeIcon />
      <UnisIcons.GoogleVoiceIcon />
      <UnisIcons.GoogleWearosIcon />
      <UnisIcons.GoogleWebDesignerIcon />
      <UnisIcons.GrammarlyIcon />
      <UnisIcons.GraphqlIcon />
      <UnisIcons.GreenlightMedicalIcon />
      <UnisIcons.GroovesharkIcon />
      <UnisIcons.GruntIcon />
      <UnisIcons.GulpIcon />
      <UnisIcons.HaikuIcon />
      <UnisIcons.HashnodeIcon />
      <UnisIcons.HealthgradesIcon />
      <UnisIcons.Html5Icon />
      <UnisIcons.IdealIcon />
      <UnisIcons.IgtvIcon />
      <UnisIcons.IndesignIcon />
      <UnisIcons.InstagramIcon />
      <UnisIcons.IntelIcon />
      <UnisIcons.IntercomIcon />
      <UnisIcons.InternationalBreastfeedingIcon />
      <UnisIcons.InternetExplorerIcon />
      <UnisIcons.InvisionIcon />
      <UnisIcons.IosIcon />
      <UnisIcons.JamstackIcon />
      <UnisIcons.JasmineIcon />
      <UnisIcons.JavaIcon />
      <UnisIcons.JavascriptIcon />
      <UnisIcons.JbClionIcon />
      <UnisIcons.JbIntellijIdeaIcon />
      <UnisIcons.JbPycharmIcon />
      <UnisIcons.JbRubymineIcon />
      <UnisIcons.JbWebstormIcon />
      <UnisIcons.JbYoutrackIcon />
      <UnisIcons.JcbIcon />
      <UnisIcons.JestIcon />
      <UnisIcons.JetbrainsIcon />
      <UnisIcons.JiraIcon />
      <UnisIcons.JoomlaIcon />
      <UnisIcons.JqueryIcon />
      <UnisIcons.JqueryMobileIcon />
      <UnisIcons.JsfiddleIcon />
      <UnisIcons.JsonIcon />
      <UnisIcons.JssIcon />
      <UnisIcons.KakaoTalkIcon />
      <UnisIcons.KayakoIcon />
      <UnisIcons.KickstarterIcon />
      <UnisIcons.KissmetricsIcon />
      <UnisIcons.KotlinIcon />
      <UnisIcons.KrakenJsIcon />
      <UnisIcons.KronosIcon />
      <UnisIcons.KubernetesIcon />
      <UnisIcons.LambdatestIcon />
      <UnisIcons.LinkedinAltIcon />
      <UnisIcons.LinkedinIcon />
      <UnisIcons.LinuxIcon />
      <UnisIcons.LinuxMintIcon />
      <UnisIcons.LoomIcon />
      <UnisIcons.LyftIcon />
      <UnisIcons.MacosIcon />
      <UnisIcons.MailchimpIcon />
      <UnisIcons.MariaDbIcon />
      <UnisIcons.MarkdownIcon />
      <UnisIcons.MarvelIcon />
      <UnisIcons.MastercardIcon />
      <UnisIcons.MaterialUiIcon />
      <UnisIcons.MazeIcon />
      <UnisIcons.MediumAltIcon />
      <UnisIcons.MediumIcon />
      <UnisIcons.MeteorIcon />
      <UnisIcons.MicrosoftAuthenticatorIcon />
      <UnisIcons.MicrosoftEdgeIcon />
      <UnisIcons.MicrosoftIcon />
      <UnisIcons.MicrosoftWindows95Icon />
      <UnisIcons.MicrosoftmsIcon />
      <UnisIcons.MiroIcon />
      <UnisIcons.MochaIcon />
      <UnisIcons.MsAzureIcon />
      <UnisIcons.MsExcelIcon />
      <UnisIcons.MsOffice360Icon />
      <UnisIcons.MsOnedriveIcon />
      <UnisIcons.MsOnenoteIcon />
      <UnisIcons.MsOutlookIcon />
      <UnisIcons.MsPowerBiIcon />
      <UnisIcons.MsPowerVirtualAgentsIcon />
      <UnisIcons.MsPowerappsIcon />
      <UnisIcons.MsPowerpointIcon />
      <UnisIcons.MsProjectIcon />
      <UnisIcons.MsSharepointIcon />
      <UnisIcons.MsStreamIcon />
      <UnisIcons.MsTeamsIcon />
      <UnisIcons.MsVisioIcon />
      <UnisIcons.MsWordIcon />
      <UnisIcons.MsXboxIcon />
      <UnisIcons.MsYammerAltIcon />
      <UnisIcons.MsYammerIcon />
      <UnisIcons.MychartIcon />
      <UnisIcons.MymicrosIcon />
      <UnisIcons.MysqlIcon />
      <UnisIcons.NativescriptIcon />
      <UnisIcons.NetflixIcon />
      <UnisIcons.NextdoorIcon />
      <UnisIcons.NfcIcon />
      <UnisIcons.NginxIcon />
      <UnisIcons.NodeJsIcon />
      <UnisIcons.NotionIcon />
      <UnisIcons.NpmIcon />
      <UnisIcons.NuanceIcon />
      <UnisIcons.NuxtJsIcon />
      <UnisIcons.OkIcon />
      <UnisIcons.OpenGraphIcon />
      <UnisIcons.OpenstackIcon />
      <UnisIcons.OperaIcon />
      <UnisIcons.OpsgenieIcon />
      <UnisIcons.PatreonIcon />
      <UnisIcons.PaypalIcon />
      <UnisIcons.PercyIcon />
      <UnisIcons.PerlIcon />
      <UnisIcons.PhpIcon />
      <UnisIcons.PhpstormIcon />
      <UnisIcons.PinterestIcon />
      <UnisIcons.PlaystationIcon />
      <UnisIcons.PolicytechIcon />
      <UnisIcons.PolymerIcon />
      <UnisIcons.PostCssIcon />
      <UnisIcons.PostgraphileIcon />
      <UnisIcons.PostgresqlIcon />
      <UnisIcons.PostmanIcon />
      <UnisIcons.PowerBiIcon />
      <UnisIcons.PreactIcon />
      <UnisIcons.PrettierIcon />
      <UnisIcons.ProcreateIcon />
      <UnisIcons.ProductHuntIcon />
      <UnisIcons.PwaIcon />
      <UnisIcons.PythonIcon />
      <UnisIcons.QuoraIcon />
      <UnisIcons.QzoneIcon />
      <UnisIcons.RLangIcon />
      <UnisIcons.RaspberryPiIcon />
      <UnisIcons.ReactIcon />
      <UnisIcons.ReactivexIcon />
      <UnisIcons.ReadmeSoIcon />
      <UnisIcons.RecaptchaIcon />
      <UnisIcons.RedditIcon />
      <UnisIcons.RedhatIcon />
      <UnisIcons.RedisIcon />
      <UnisIcons.ReduxIcon />
      <UnisIcons.RubyIcon />
      <UnisIcons.RubygemsIcon />
      <UnisIcons.SafariIcon />
      <UnisIcons.SalesforceIcon />
      <UnisIcons.SassIcon />
      <UnisIcons.SaucelabsIcon />
      <UnisIcons.SeleniumIcon />
      <UnisIcons.SemanticUiIcon />
      <UnisIcons.ServicenowIcon />
      <UnisIcons.SharecareIcon />
      <UnisIcons.ShazamIcon />
      <UnisIcons.ShopifyIcon />
      <UnisIcons.SignalIcon />
      <UnisIcons.SitecoreIcon />
      <UnisIcons.SketchIcon />
      <UnisIcons.SkypeIcon />
      <UnisIcons.SlackIcon />
      <UnisIcons.SmartSquareIcon />
      <UnisIcons.SnapchatAltIcon />
      <UnisIcons.SnapchatIcon />
      <UnisIcons.SolrIcon />
      <UnisIcons.SoundcloudIcon />
      <UnisIcons.SourcetreeIcon />
      <UnisIcons.SpectrumIcon />
      <UnisIcons.SpotifyIcon />
      <UnisIcons.SquareIcon />
      <UnisIcons.SquarespaceIcon />
      <UnisIcons.StackoverflowIcon />
      <UnisIcons.StarkIcon />
      <UnisIcons.StatuspageIcon />
      <UnisIcons.SteamIcon />
      <UnisIcons.StorybookIcon />
      <UnisIcons.StripeIcon />
      <UnisIcons.StumbleUponIcon />
      <UnisIcons.SublimetextIcon />
      <UnisIcons.SvelteIcon />
      <UnisIcons.SvgIcon />
      <UnisIcons.SwaggerIcon />
      <UnisIcons.SwiftAltIcon />
      <UnisIcons.SwiftIcon />
      <UnisIcons.SymantecIcon />
      <UnisIcons.SymfonyIcon />
      <UnisIcons.TableauIcon />
      <UnisIcons.TailwindCssIcon />
      <UnisIcons.TechCrunchIcon />
      <UnisIcons.TecsysIcon />
      <UnisIcons.TelegramIcon />
      <UnisIcons.TensorflowIcon />
      <UnisIcons.TerraformIcon />
      <UnisIcons.TestcafeIcon />
      <UnisIcons.TestprojectIcon />
      <UnisIcons.TikTokIcon />
      <UnisIcons.TinderIcon />
      <UnisIcons.TinkoffIcon />
      <UnisIcons.TreehouseIcon />
      <UnisIcons.TrelloIcon />
      <UnisIcons.TripadvisorIcon />
      <UnisIcons.TumblrIcon />
      <UnisIcons.TwilioIcon />
      <UnisIcons.TwitchIcon />
      <UnisIcons.TwitterIcon />
      <UnisIcons.TwitterSpacesIcon />
      <UnisIcons.TwitterVerifiedBadgeIcon />
      <UnisIcons.TypescriptIcon />
      <UnisIcons.UberIcon />
      <UnisIcons.UbuntuIcon />
      <UnisIcons.UcIcon />
      <UnisIcons.UikitIcon />
      <UnisIcons.UnionpayIcon />
      <UnisIcons.UsertestingIcon />
      <UnisIcons.V8Icon />
      <UnisIcons.V8IgnitionIcon />
      <UnisIcons.V8TurbofanIcon />
      <UnisIcons.ViberIcon />
      <UnisIcons.VimeoAltIcon />
      <UnisIcons.VimeoIcon />
      <UnisIcons.VisaIcon />
      <UnisIcons.VisualStudioIcon />
      <UnisIcons.ViteJsIcon />
      <UnisIcons.VivaldiIcon />
      <UnisIcons.VkIcon />
      <UnisIcons.VsCodeIcon />
      <UnisIcons.VueIcon />
      <UnisIcons.W3CIcon />
      <UnisIcons.WazeIcon />
      <UnisIcons.WeTransferIcon />
      <UnisIcons.WebDevIcon />
      <UnisIcons.WebFundamentalsIcon />
      <UnisIcons.WebmoneyIcon />
      <UnisIcons.WebpackIcon />
      <UnisIcons.WechatIcon />
      <UnisIcons.WeiboIcon />
      <UnisIcons.WesternUnionIcon />
      <UnisIcons.WhatsappIcon />
      <UnisIcons.WikipediaIcon />
      <UnisIcons.WindowsIcon />
      <UnisIcons.WordpressIcon />
      <UnisIcons.WorldPayIcon />
      <UnisIcons.WrikeIcon />
      <UnisIcons.YahooIcon />
      <UnisIcons.YandexIcon />
      <UnisIcons.YandexKassaIcon />
      <UnisIcons.YandexMusicIcon />
      <UnisIcons.YelpIcon />
      <UnisIcons.YoutubeIcon />
      <UnisIcons.YoutubeMusicIcon />
      <UnisIcons.ZapierIcon />
      <UnisIcons.ZendeskIcon />
      <UnisIcons.ZeplinIcon />
      <UnisIcons.ZoomIcon />
    </div>
  );
}

export default App;
